export const FETCH_MORE = "FETCH_MORE";
export const FETCH_MORE_SUCCEDDED = "FETCH_MORE_SUCCEDDED";

export const FETCH_SEARCH = "FETCH_SEARCH";
export const FETCH_SEARCH_SUCCEDDED = "FETCH_SEARCH_SUCCEDDED";

export const FETCH_CHAR_DATA_REQUESTED = "FETCH_CHAR_DATA_REQUESTED";
export const FETCH_CHAR_DATA_SUCCEDED = "FETCH_CHAR_DATA_SUCCEDED";

export const FETCH_DATA_SUCCEEDED = "FETCH_DATA_SUCCEEDED";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const FETCH_DATA_REQUESTED = "FETCH_DATA_REQUESTED";
